/// <reference types="node" />
import ReactionMessage from '../messages/ReactionMessage';
import { Media } from '../messages/MediaMessage';
import ChatStatus from '../modules/chat/ChatStatus';
import Message from '../messages/Message';
import { BotStatus } from './BotStatus';
import IAuth from '../client/IAuth';
import BotEvents from './BotEvents';
import Chat from '../modules/chat/Chat';
import User from '../modules/user/User';
import IBot from './IBot';
import Call from '../models/Call';
export default class BotBase extends BotEvents implements IBot {
    id: string;
    status: BotStatus;
    phoneNumber: string;
    name: string;
    profileUrl: string;
    connect(auth: IAuth): Promise<void>;
    reconnect(alert?: boolean): Promise<void>;
    stop(reason: any): Promise<void>;
    logout(): Promise<void>;
    send(message: Message): Promise<Message>;
    sendMessage(chat: Chat | string, message: string | Message, mention?: Message): Promise<Message>;
    editMessage(message: Message): Promise<void>;
    addReaction(message: ReactionMessage): Promise<void>;
    removeReaction(message: ReactionMessage): Promise<void>;
    readMessage(message: Message): Promise<void>;
    removeMessage(message: Message): Promise<void>;
    deleteMessage(message: Message): Promise<void>;
    downloadStreamMessage(media: Media): Promise<Buffer>;
    getBotName(): Promise<string>;
    setBotName(name: string): Promise<void>;
    getBotDescription(): Promise<string>;
    setBotDescription(description: string): Promise<void>;
    getBotProfile(lowQuality?: boolean): Promise<Buffer>;
    getBotProfileUrl(lowQuality?: boolean): Promise<string>;
    setBotProfile(image: Buffer): Promise<void>;
    getChats(): Promise<string[]>;
    setChats(chats: Chat[]): Promise<void>;
    getChat(chat: Chat): Promise<Chat | null>;
    updateChat(chat: {
        id: string;
    } & Partial<Chat>): Promise<void>;
    removeChat(chat: Chat): Promise<void>;
    createChat(chat: Chat): Promise<void>;
    leaveChat(chat: Chat): Promise<void>;
    addUserInChat(chat: Chat, user: User): Promise<void>;
    removeUserInChat(chat: Chat, user: User): Promise<void>;
    promoteUserInChat(chat: Chat, user: User): Promise<void>;
    demoteUserInChat(chat: Chat, user: User): Promise<void>;
    changeChatStatus(chat: Chat, status: ChatStatus): Promise<void>;
    getChatUsers(chat: Chat): Promise<string[]>;
    getChatAdmins(chat: Chat): Promise<string[]>;
    getChatLeader(chat: Chat): Promise<string>;
    getChatName(chat: Chat): Promise<string>;
    setChatName(chat: Chat, name: string): Promise<void>;
    getChatDescription(chat: Chat): Promise<string>;
    setChatDescription(chat: Chat, description: string): Promise<void>;
    getChatProfile(chat: Chat, lowQuality?: boolean): Promise<Buffer>;
    getChatProfileUrl(chat: Chat, lowQuality?: boolean): Promise<string>;
    setChatProfile(chat: Chat, profile: Buffer): Promise<void>;
    joinChat(code: string): Promise<void>;
    getChatInvite(chat: Chat): Promise<string>;
    revokeChatInvite(chat: Chat): Promise<string>;
    rejectCall(call: Call): Promise<void>;
    getUsers(): Promise<string[]>;
    setUsers(users: User[]): Promise<void>;
    getUser(user: User): Promise<User | null>;
    updateUser(user: {
        id: string;
    } & Partial<User>): Promise<void>;
    removeUser(user: User): Promise<void>;
    unblockUser(user: User): Promise<void>;
    blockUser(user: User): Promise<void>;
    getUserName(user: User): Promise<string>;
    setUserName(user: User, name: string): Promise<void>;
    getUserDescription(user: User): Promise<string>;
    setUserDescription(user: User, description: string): Promise<void>;
    getUserProfile(user: User): Promise<Buffer>;
    getUserProfileUrl(user: User, lowQuality?: boolean): Promise<string>;
    setUserProfile(user: User, profile: Buffer): Promise<void>;
}
